### PR TITLE
counters: use big-integers to avoid overflows

### PR DESCRIPTION
**Pull request by lucab**
Do not panic if the overall counter payload overflows `u64`.

### CODE REVIEW

**Comment by lucab** [comment]
@davidrusu @spacejam this is explicitly called out in Shapiro's paper.
Individual clocks have a similar corner-case on increment, but I'm not sure what the behavior should be in that case.

**Comment by davidrusu** [comment]
@lucab good catch, how about we widen the computed counter value to a `u128/i128` type instead of wrapping in an optional?

**Comment by lucab** [comment]
@davidrusu that requires rustc >= 1.26.0. If you are fine with that, I can switch to it. I think it is reasonable to expect less than 2^64 replicas.

However, there is still the the unsigned-to-signed cast in pncounter which is inherently incorrect on any width. Should that still return an optional integer or do you have better ideas?

**Comment by davidrusu** [comment]
@lucab Hmm, `PNCounter` is a more difficult case.

It may be time to introduce a big num dependency, I don't think anyone using a CRDT counter should mind the extra overhead from the big num.

What are your thoughts on using big nums here, if you aren't against it, would you mind making the change to use big nums when computing the counter value?
https://github.com/rust-num/num-bigint looks like a nice big int crate in pure rust.

We should be OK to leave `VClock` counters as `u64`'s for now, although... the library does have aspirations to generate webasm bindings to bring these CRDT's to the browser. At that point, we will need to think about what to do about the `u64` counters in the `VClock`'s since JS only has ~53 bits of precision.
I've updated the webasm ticket to track this: #16 

Also a heads up that I'm about to merge #29 which will introduce conflicting changes to this part of the code base.

**Comment by davidrusu** [comment]
re: `u128/i128 requires rustc >= 1.26.0`
That's fine we're targeting only the latest stable rust release for now, perhaps once the CRDT api stabilizes we can think about supporting more rust versions.

**Comment by lucab** [comment]
Ack. I've rebased this on top of #29 and to use big integers, let me know if you like it better now. However, I think that `num_bigint` is currently not compatible with WASM.

**Comment by davidrusu** [comment]
@lucab looks good! mind rebasing against master once more to clean up the history (#29 is merged in)

**Comment by lucab** [comment]
Ok, done.

**Comment by davidrusu** [comment]
Thanks @lucab :)

**Pull request merged**
